FROM node:22-alpine

WORKDIR /app

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@10.18.3 --activate

# On copie seulement les fichiers de dépendances pour installer au début
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

# Pour le dev : on montera le code en volume

ENV NUXT_TELEMETRY_DISABLED=1
ENV HOST=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["pnpm", "dev", "--host", "0.0.0.0", "--port", "3000"]
